version: "3.7"

services:
    app:
        image: maude-npa-app
        build:
            context: .
            dockerfile: dockerfile
        working_dir: /app
        volumes:
            - ./:/app
        stdin_open: true
        tty: true
